In [52]:
#ML STEPS
#1. DATA PREPROCESSING
#2. MODELLING
#3. EVALUATION

In [53]:
#DATA PREPROCESSING
# SPLIT DATA TO TRAIN(80%) & TEST DATA(20%)
#FEATURE_SCALING is applied to cols 

In [54]:
#TYPES OF FEATURES
#NORMALIZATION -> (x-Xmin)/Xmax-Xmin => the values range between 0 & 1
#STANDARDIZATION -> (x-xavg)/stddev = > the values range between -3 & 3

In [55]:
import pandas as pd
import numpy as np

In [56]:
dataset = pd.read_csv('../datasets/Data PreProcessing/Data.csv')

In [57]:
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [58]:
#Handelling missing values for Age & Sal
from sklearn.impute import SimpleImputer
imp = SimpleImputer(missing_values=np.nan, strategy='median')

In [59]:
x[:,1:3] =imp.fit_transform(x[:,1:3])

In [60]:
#X[:,1:3] = imp.transform(X[:,1:3])
dataset.iloc[:, :-1] =x

In [61]:
print(dataset)

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0  61000.0       Yes
5   France  35.0  58000.0       Yes
6    Spain  38.0  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes


In [62]:
#Encoding Categorial Values
#https://analyticsindiamag.com/a-complete-guide-to-categorical-data-encoding/#:~:text=Encoding%20categorical%20data%20is%20a,provided%20to%20the%20different%20models.&text=In%20the%20field%20of%20data,preparation%20is%20a%20mandatory%20task.

In [63]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

#https://scikit-learn.org/stable/modules/generated/sklearn.compose.ColumnTransformer.html

In [64]:
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

C:\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:395: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  check_array(X, dtype=np.int)
C:\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:110: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release not

In [65]:
print(x)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 61000.0]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.0 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [66]:
# Encoding the Dependent Variable
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
print(y)

[0 1 0 0 1 1 0 1 0 1]


In [67]:
#Test Train Split
#test set & Train data set split should be done before feature scaling because 
#while  calculating standard dev in feature scaling the test should have 0 effect in train set
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test =train_test_split(x,y,test_size=0.2,random_state=1)


In [68]:
print(X_train,end="\n*****************\n")
print(X_test,end="\n*****************\n")
print(Y_train,end="\n*****************\n")
print(Y_test)

[[0.0 0.0 1.0 38.0 52000.0]
 [0.0 1.0 0.0 40.0 61000.0]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]
*****************
[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]
*****************
[0 1 0 0 1 1 0 1]
*****************
[0 1]


In [69]:
#FeatureScaling
# two types 1) standardisation 2) Normalisation

In [70]:
from sklearn.preprocessing import StandardScaler

In [71]:
sc = StandardScaler()
print(X_train[:,3:])

[[38.0 52000.0]
 [40.0 61000.0]
 [44.0 72000.0]
 [38.0 61000.0]
 [27.0 48000.0]
 [48.0 79000.0]
 [50.0 83000.0]
 [35.0 58000.0]]


In [72]:
X_train[:,3:] = sc.fit_transform(X_train[:,3:])

In [74]:
X_test[:,3:] = sc.transform(X_test[:,3:])

In [75]:
print(X_test)

[[0.0 1.0 0.0 -1.4471492105848434 -0.8727355967528775]
 [1.0 0.0 0.0 -0.434144763175453 0.2341485747385769]]
